### ISSUE TITLE
[question] Is it possible to inherit from two Redux mixins ?

### ISSUE THREAD

**Issue by NeilujD** [tur-nr/polymer-redux#102]
Hi !
I made a custom `mixin` using polymer-redux.
My `mixin` works good with any of my elements.
But I would like to have an element that inherit from my `mixin` and another Redux `mixin` and it seems that it is breaking the Redux workflow.
It is probably an issue about the `properties` or `actions` replacement by inheritance but more importantly, is it even possible to combine two different Redux stores ?
Is it an approach that should be possible or is it a bad use of Redux ?

**Comment by tur-nr** [comment]
Although Redux does allow multi store creations, it actually recommends against it.

> Instead, there is just a single store with a single root reducing function. As your app grows, instead of adding stores, you split the root reducer into smaller reducers independently operating on the different parts of the state tree... [more](http://redux.js.org/docs/api/Store.html#a-note-for-flux-users)

**Comment by NeilujD** [comment]
Ok so what if I want to publish a specific Redux mixin to permit the community to use it in their app. It means that they can not use mine and theirs in the same element right ?
Is there a workaround about this ?

**Comment by tur-nr** [comment]
If you are writing an Element to publish for the community, I would suggest you don't write a ReduxMixin at all. Otherwise you are coupling Redux to any consuming application. They may not want to use Redux as their state management.

So I would advise that you write your Elements to be unaware of any state management library. Allow applications to make that choice.

What you can do is provide two things.

1. Elements with no state management.
3. Reducer incase the consuming application already has polymer-redux setup.

This way if they application hasn't got Redux setup they can use your Mixin. If they do, they will just combine your reducer.

_Library Element_

```js
export default class Foo extends Polymer.Element {
    static get is() { return 'x-foo'; }

    static get properties() {
        return {
            bar: {
                type: Boolean,
                value: false,
            } 
        };
    }
}
```

_Library Reducer_

```js
export default (state, action) => {
    return state; // do foo changes
}
```

_Application ReduxMixin_

```js
import {reducer} from 'library';

const store = Redux.createStore(reducer);
const ReduxMixin = PolymerRedux(store);
```

_Application Element_

```html
<template>
    <x-foo bar="[[bar]]"></x-foo>
</template>

<script>
    export default class ApplicationFoo extends ReduxMixin(Polymer.Element) {
        static get is() { return 'app-foo'; }

        static get properties() {
            return {
                bar: {
                    type: Boolean,
                    statePath: 'foo',
                } 
            };
        }
    }
</script>
```

**Comment by NeilujD** [comment]
Ok I understand.
Then, as you can not have more than one store in your app you can not have more than one ReduxMixin in your app.
But still you need to specify the actions in the element right ?

**Comment by tur-nr** [comment]
You can have as many stores and mixing as you wish. But each mixin can only
have one store. And each element can only have one mixin.

**Comment by NeilujD** [comment]
Thank for your answers and your tips ! I close the issue.
