### ISSUE TITLE
Wrong state sent to element

### ISSUE THREAD

**Issue by magnonellie** [tur-nr/polymer-redux#105]
I don't have a test case to reproduce this or anything, but in my app, the state sent down to my dynamic selector was not in sync with the main state for some reason. I could see this being the cause of changing the state after a state change with observers, but other than that, I have no clue really. If I call MyApp.store.getState() in the selector, I get the correct state.

**Comment by tur-nr** [comment]
Are you using [Redux DevTools](https://github.com/gaearon/redux-devtools)? Does the initial state look the same as the state whenever actions have been dispatched? If the state doesn't look the same, are you using [`combineReducers`](http://redux.js.org/docs/api/combineReducers.html), sometimes this trips people up.

**Comment by magnonellie** [comment]
I am using both of those and it hasn't been causing any issues before on my medium-sized app. It's just now that I encountered the issue and I haven't been able to solve it despite a lot of debugging.

**Comment by tur-nr** [comment]
So when the application is initialised is the state correct?

**Comment by magnonellie** [comment]
As far as I can tell, yes. My problem is that I have an array with objects inside which is seemingly referencing an old version in the selector. It's supposed to have two objects inside of it but it only has one. Again, my main store does have the correct value, but that's not passed down to the selector.

**Comment by tur-nr** [comment]
If you were to dispatch the action via the Redux DevTools, can you examine the state. I want to rule out any connection to Polymer or the bindings first. Without samples or test cases I can't help much 😿

**Comment by magnonellie** [comment]
If I dispatch the first action that causes the bug, the bug occurs. However, when dispatched, I also have a component dispatching another action based on that action (through an observer). Just dispatching the second action propagates the state fine (but doesn't cause the correct behavior obviously).

**Comment by tur-nr** [comment]
If you have dispatched an action through dev tools and the state
represented in the dev tools is incorrect then this closes this issue I'm
afraid.

If I'm unable to see your code then I can only presume the issues lies
within your reducer. Here's a quick check list for debugging your reducer.

- always return new state
- don't hold reference to arrays/objects
- check your combineReducer logic is correct
- are you using any middeware, what's it doing exactly

**Comment by magnonellie** [comment]
Again, the state itself has always been correct. This is not an issue with my reducers. Those I have already debugged and tested quite well. :smile: The problem is in the state that's passed down to my element through polymer-redux.

I'm gonna try to write a test case for it right now.

**Comment by tur-nr** [comment]
If you are using dynamic selectors polymer-redux just pushes the whole state into them;

_Get the state from redux and call upate_
https://github.com/tur-nr/polymer-redux/blob/master/src/index.js#L74-L75

_Pass the state into dynamic selectors_
https://github.com/tur-nr/polymer-redux/blob/master/src/index.js#L61

A test case would help greatly, thanks.

**Comment by tur-nr** [comment]
I see what you mean now from the test cases. Thanks for writing those. I thought you had done the dispatches from Redux dev tools and reviewed the state there which lead me to believe there was no part of the bindings in play.

Ok I'm sure this issue has come up before, I will trying look over the issues history. But in the meantime what you need to do is the following inside your observer.

```js
Polymer.Async.microTask.run(() => this.dispatch('bar'));
```

And here is the reason why; Observers will happen immediately in Polymer which is kinda shit because whilst polymer-redux is in the loop of checking for updates and making changes Polymer has already dispatched the next action against an incomplete state update. So review the control flow:

1. Dispatch action A.
2. Redux state changes.
3. PolymerRedux begins checking for updates.
4. PolymerRedux changes foo.
5. Polymer catches a change to foo.
6. PolymerRedux dispatches action B.
7. Redux state changes (but PolymerRedux is still in the middle of it's update loop for foo).
8. PolymerRedux begins checking for updates.
9. PolymerRedux changes bar (but now we are running two update loops).

**Comment by magnonellie** [comment]
Yeah, I kinda figured out observers are synchronous when I saw the enormous stack trace I had. :laughing: 
Anyway, thank you for taking your time to explain! Should we close or keep open?

**Comment by tur-nr** [comment]
I feel like we should maybe document this as you're definitely not the only one that has encountered this. Lets leave this open and I shall document this closing this issue.

Thanks for your contribution 👍

**Comment by tur-nr** [comment]
@magnonellie we owe @mkorenko a beer 🍻 😆  your test cases pass with his PR.
