### ISSUE TITLE
Caveats and best practice in README

### ISSUE THREAD

**Issue by tur-nr** [tur-nr/polymer-redux#13]
Demonstrating the caveats and gotchas in the README. Also best practice when using Polymer with Redux.

Things to mention:
- [ ] **Don't** modify properties/state inside Polymer, always dispatch.
- [ ] Observing _objects_ and _array_ changes in Polymer.
- [ ] Highlight principle 3 of redux, changing state.

**Comment by devinivy** [comment]
Related to this– immutable data isn't as beneficial to Polymer as it is to React.  In React immutable data allows the decision to rerender a particular component to be a series of simple pointer comparisons.  In Polymer we typically describe the mutations to a component's state using an API (`set()`, `push()`, etc.), and that lets Polymer make performant adjustments to the DOM.  This complicates the relationship between Polymer and Redux's third principle, and I look forward to a workable solution.  I've been looking into the approach that cerebral's state tree takes (https://github.com/cerebral/state-tree), where changes to state can be flushed/described.  This could work well with Polymer's `notifyPath()` / `notifySplices()`.

**Comment by cvanleeuwen** [comment]
@devinivy I'm also really concerned with Polymer's data binding and immutable data. Seeing posts like https://github.com/Polymer/polymer/issues/3762. 

I've had weird behavior in dom-repeaters and change notifications in Polymer. So much that I've started replacing Polymer's dom-repeater and data binding by React. Given that Polymer elements are really 'just' dom elements, its pretty straight forward hand over the composition to React instead. So far this works pretty nice, but its really early to be sure.

**Comment by tur-nr** [comment]
@devinivy this is true, it complicates matters that the mutation methods can be called outside of the `ReduxBehavior`. This is a principle `polymer-redux` needs to document, that if you're using it for managing state within an Element, then any other mutations outside of Redux **_should_** be illegal.

@cvanleeuwen If you keep everything inside the Redux store I think it works really well. Given the example from Polymer/polymer#3762 if that was to move to a Redux store, the objects should keep the `id` and `templateId` within the same item rather than relying on the `dom-repeat` and a global counter. Even tho this an issue within Polymer, the example looks like a code smell to me.

**Comment by devinivy** [comment]
Polymer's data-binding generally has not given me any trouble.  Perhaps the behavior of databinding notifications is not well-understood, but I think it is quite sensible once you get the hang of it.  When folks try to use immutable data with Polymer and it doesn't work as expected, it always seems to be due to some sort of misunderstanding or misuse.  Polymer provides low-level APIs that can allow immutable data to work (though little effort has gone into this on the part of the community), but Polymer ultimately relies on having descriptions of mutations to make data-binding work.

Even in this case I think polymer-redux gives-up a certain amount of performance in exchange for the ability to use plain, immutable objects in the store.  For example, if you observe `x` in a Polymer component and update `x.deep.deeper` in your reducer, then _every single property_ under `x` will be notified in Polymer-land.  You can also see this library calculates splices, where typically those splices would be described directly to Polymer when using `this.splice()` or `this.push()`.

In any case, there's a lot of work to be done here and it's certainly not the fault of this library that it doesn't deal with that.  I'm just curious if anyone has any ideas how we can make using Polymer with Redux better, and ease this little bit of friction!

**Comment by cvanleeuwen** [comment]
@tur-nr https://github.com/Polymer/polymer/issues/3762 mentions he's already using Redux. The global counter is there to see when Polymer creates a new element instances.

What do you mean by:

> the objects should keep the id and templateId within the same item rather than relying on the `dom-repeat`

As I see it, the best to do it is always/only bind to Array bindings through polymer-redux via `statePath`, otherwise changes won't get notified. What inspired you to add the Array notifications to polymer-redux?

**Comment by tur-nr** [comment]
@cvanleeuwen I can't see anywhere in his example where he uses Redux. Maybe the example is just a mimic of what he has implemented within his application. But from the example `my-element` holds an array of objects, `{ id: <Number> }` and then he repeats on these items in `my-element`. Another element, `repeater-item`, keeps the `templateId` state. This means that `id` and `templateId` are states that have a relationship with a row/cell. Yet their values are stored separately,  `id` on `my-element` and `templateId` on `repeater-item`. Would it be best practice to consolidate these so that it would be an array of objects, `{ id: <Number>, templateId: <Number>}` that is set on `my-element` and then `repeater-item` gets the `templateId` injected.

Well actually there was inspirations per se, it was a bug #12 which I decided to calculate the splices between arrays.

**Comment by cvanleeuwen** [comment]
@tur-nr you're right, the sample isn't using redux, he only mentions it.

The purpose of `templateId` in that sample is to see how `dom-repeat` creates/re-uses dom-nodes when new data is bound. The issue is when Polymer gets a new Array; it loses track of which array item was bound to which node, then detaches everything and re-uses previously created nodes.

So basically it's about performance; especially when elements are semi-statefull (e.g. rendered svg charts), changing Arrays would mean full re-renders of all items in the `dom-repeat`.

**Comment by kritollm** [comment]
I also thought of this optimisation, but dropped it precisely because doom repeat re draws all items when the array reference change. One way to solve it is to have a proxy object that listens to array change and then do a manual update with polymers array mutation methods.

Maybe you can do something like this: `splice(path, 0, oldArrayLength, newArray);`

**Comment by tur-nr** [comment]
@kritollm yes we could do this. By pass the strict equality check on arrays and calculate splices instead. Providing that all mutations of the array go through a Redux action, `polymer-redux` will calculate each splice accordingly. The elements property and store state will seem to be in sync but will reference different arrays.

How would we work this with deep objects, described above by @devinivy

**Comment by cvanleeuwen** [comment]
To get a solid solution we'd need to diff the entire object graph (starting at `statePath`), to calculate the changes needed to correctly Polymer (`notifySplices` and `notifyPath`). Also we'd need to keep Polymer in the dark about changes (so refrain using `this.set`), otherwise it will already trigger an update.

So basically it's as @devinivy mentioned; get a way to calculate or record all changes which have been made.

**Comment by devinivy** [comment]
This is why I like the approach of https://github.com/cerebral/state-tree, which allows you to flush a description of changes to the state tree as needed.  Those changes could be fed into Polymer with `notify()` and `notifySplices()`.  That's a mutable state tree though, and maybe it would break time-travel.  I think we need a tool outside of polymer-redux to make this work– perhaps polymer-redux could "support" that tool and influence its API.

I took a shot at solving this with Reflux (https://github.com/devinivy/funk).  The stores are actually Polymer components with mutable state whose changes get passed along to all interested components.  The approach has downsides, but what it does achieve is granular data-binding to global state– it perfectly maintains deep property changes and array splices without any computation/dirty-checks.

**Comment by tur-nr** [comment]
What about https://github.com/flitbit/diff, if the property is an object we can run it through `diff` and if any changes can use `applyDiff` and then notify Polymer accordingly?

**Comment by tur-nr** [comment]
I've tried to over cover immutable data issues, but it's seems like a bigger task than `polymer-redux`. The issue lies deep within how Polymer calculates the changes of state. It holds references unfortunately via `Polymer.Collection`.

I have branch `immutable` that tries to calculate necessary state changes so that we don't have to change the reference when we update properties. Arrays are proving difficult, seems like the dom and state get out of sync when removing items. Perhaps internal cache?

**Comment by timeu** [comment]
For the best-practices I would also describe  the seperation between container and presentational components (https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.ffzyxvtbq). 
Originally it was written with React components in mind but it works as well with Polymer components. 
Try to create as many (stateless) presentational components in Polymer and when necessar create smart container components that implement the `ReduxBehavior`. 
It might also help a bit with the problem of immutability and polymer's data-binding issues (as mentioned in this issue)

**Comment by timeu** [comment]
FYI: Polymer 2.x will make it easier to integrate with Flux like state management frameworks: 

https://github.com/Polymer/polymer/tree/2.0-preview

**Comment by tur-nr** [comment]
@timeu this is great news. Have you worked with yet? I would like to spike a branch with Polymer-Redux to see how it works :)

**Comment by devinivy** [comment]
The core difference is that nested objects/arrays are assumed to be dirty.  This exhibits the change in behavior pretty well: https://github.com/Polymer/polymer/issues/3603.  The changes in Polymer v2 are by no means a silver bullet, but they are nice!  The largest improvements will be on the side of state management interop with Polymer, not Polymer interop with state management.

**Comment by timeu** [comment]
@devinivy: IMHO the improvements specifically targeting the state management side interop with Polymer is probably more important than the reverse one because AFAIK state should anyways only be mutated through reducers that react to actions that are fired from the Polymer elements.

**Comment by tur-nr** [comment]
Guys I have a working branch,  [`polymer-2`](https://github.com/tur-nr/polymer-redux/tree/polymer-2), for Polymer 2.0, the logic for the bindings is really nice.

**Comment by timeu** [comment]
@tur-nr great work. Can you maybe summariize the main differences between 1.x and 2.x  with regard to redux. I will have a look at the 2.0 branch but it would be still nice to get your take on it

**Comment by kristfal** [comment]
With regard to aspect 1):

I'm wondering if `polymer` properties with `statePath` should be designated by `polymer-redux` as `readOnly: true`. That way, the regular syntax of `this.foo = bar` and `this.set('foo', 'bar')` would throw errors. 

Pros: It could potentially make it easier for new users of redux to follow the core principles. 
Cons: It would make the bindings more opinionated.

@tur-nr what is your feeling about this?

**Comment by mdgbayly** [comment]
Just trying to follow along with some of this discussion...
Regarding the treatment of arrays and adding/removing items without mutating the redux array, are the comments above stating that currently in Polymer with a dom-repeat, that will cause Polymer to re-render all the array items?  Because all it sees is that the array has changed.  Or is it ok for the basic case, because it sees that the items in the array are still the same objects?

**Comment by tur-nr** [comment]
@mdgbayly Polymer and Polymer-Redux does both a dirty check for arrays. Subsequently `dom-repeat` will cause re-rendering.

We tried to add smarts into Polymer-Redux to handle this behaviour using Polymer's splicing mechanism and then applying the changes over the top. This meant we were holding reference to all the possible states of the array and doing Polymer's job essentially.

@ronnyroeller wrote a good article about this issue; https://medium.com/collaborne-engineering/stop-polymer-lists-from-flickering-b2736d56a2e1

The Polymer team have been working on this data flow issue on v2. v2 does not dirty check anymore and now has the smarts built in, which makes Polymer-Redux work perfectly. There is a branch for v2.0, but it is unstable and not ready due to the ongoing development in Polymer 2.

If you are using v1 then I would suggest using the approach above in the Ronny's article.

**Comment by devinivy** [comment]
>v2 does not dirty check anymore and now has the smarts built in
@tur-nr I haven't seen this yet. It's built into dom-repeat?  As I understand it v2 simply assumes deep objects are dirty and notifies more liberally.

**Comment by tur-nr** [comment]
I was only going by their post below on 2.0 Preview, I haven't read into the code as of yet.

https://www.polymer-project.org/2.0/docs/about_20#no-more-dirty-checking-for-objects-and-arrays
