### ISSUE TITLE
Observers firing twice on chained observed dispatches

### ISSUE THREAD

**Issue by kristfal** [tur-nr/polymer-redux#41]
When a `dispatch` triggers an `observer` which in turn triggers a `dispatch` and finally triggers a second observer, the second observer is fired twice. Once with the old value, and then directly after with the new value.

Current workaround is to wrap the first observer function in an `async` call. This dispatch chain is an antipattern of redux, but it should at least not misbehave like it does right now.

Code sample:

```
actions: {

  dispatchObj1: function(obj) {
    return {
      type: 'OBJ_1_DISPATCH',
      obj: obj
      }
  },

  dispatchObj2: function(obj) {
    return {
      type: 'OBJ_2_DISPATCH',
      obj: obj
      }
  }

},
properties: {

  obj1: {
    type: Object,
    statePath: 'obj1sp',
    observer: '_onObj1Change'
  },

  obj2: {
    type: Object,
    statePath: 'obj2sp',
    observer: '_onObj2Change'
  }

},

ready: function(){
  this.dispatch('dispatchObj1', {foo:' bar'});
},

_onObj1Change: function(change) {
  console.log(change); // (foo: bar}
  this.dispatch('dispatchObj2, {...change, bar: 'lal'});
},

_onObj2Change: function(change) {
  console.log(change) // null -> {foo: bar, bar: lal}
}


.... hotfix:

_onObj1Change: function(change) {
  console.log(change); // (foo: bar}
  this.async(function(){
    this.dispatch('dispatchObj2, {...change, bar: 'lal'});
  });
}


```

**Comment by tur-nr** [comment]
If this dispatch chain is an anti-pattern of Redux then I think the Behavior shouldn't be covering for code that uses this. I'm sorry I don't see this as an issue, but rather a decision with why you are using an anti-pattern.

**Comment by kristfal** [comment]
Hey,

the chain is kind of frowned upon when using react + redux, but it does make a bit more sense in polymer. It should be noted that observing the store via `ReduxStore.subscribe((change)=> {})` does not show these 'flickering' state changes. It is only the polymer bindings, which made debugging this behavior pretty tricky.

With regards to the decision for using this pattern: Unless you use a redux router, this chain might be typical to run:

1. Route change (via page.js or something similar) -> `dispatch` route data to store
2. On route data change -> `dispatch` view selection from a high-level polymer view selector element
3. On view change -> `dispatch` initial state of new view (typically a toolbar title or something similar that is handled by a different element, but related to the view)

One could argue that all these three actions should be re-composed into a single action or two actions, but I feel that this breaks with polymer's encapsulation, placing too much responsibility on the route observer. 

I'm personally leaning towards making my view-selectors not state bound to redux, skipping call 2. via redux, but I wouldn't be surprised to see others experiencing this issue down the road.

All inn all though, I really enjoy using Redux and Polymer. I think Polymer is a lot better with a single state tree. I don't mind having it the way it is now, but if it stays, the issue should probably be covered in the readme as it was pretty tough to debug.

**Comment by tur-nr** [comment]
I think maybe you are correct with combining those actions into a single dispatch, `ROUTE_CHANGED`.

I would be against dispatching actions inside observers entirely. Simply because you as the developer need to be aware of a dispatch chain. If you're not fully aware of what observing property dispatches which action, you could become very lost or trip up very easily on looping actions.

**Comment by ZepAviator** [comment]
I'm curious to what a good pattern for Redux in Polymer would be to keep UI State current?

Say you have a long list of toggle states in maybe a settings page. All these settings are in the store and these are kept in local-storage to persist between sessions. 

Each toggle has an observer for when they are changed, which updates the state. Which then updates the UI (in turn, really just doing nothing since the new state matches the now set toggle). This is totally fine in operation, but on first draw, there is a moment where all toggles are updated, observed, and state loop begins. 

I got around the problem in a janky way where I put a minor debounce on the state broadcast. I don't love it though. 

Listening to tap/click events is obviously a better solution as the loop only goes around once. However in Polymer-land, it would be nice to take advantage of dispatch. If you're using something like Facebook React you get your render() method to draw that first state and then you could easily use observers from that point with lower risk of a loop...
