### ISSUE TITLE
Question: What is the recommended way to bootstrap a component's data from an API call

### ISSUE THREAD

**Issue by mdgbayly** [tur-nr/polymer-redux#44]
Great work on this project by the way. Interesting stuff.
Trying to get a feel for how best to use this lib when making backend API calls.

In React, one approach we've used to load the initial component data from an API is to dispatch an API action from componentDidMount.

So I've added a similar dispatch call to my Polymer component's ready callback.
It seems to work OK, but wondering if there are better approaches?

Thanks

**Comment by tur-nr** [comment]
If you wished to put this logic inside of an Element, you are on the right lines using the components `ready` lifecycle event.

The way I see it, is you only have two options when loading initial state into components.

**Option A**
_Outside of Elements_

This approach would be to load the data outside of the scope of the Elements. So this would be done wherever you setup your store and just dispatch an event after. Don't worry about your components as whenever they are created they fetch whatever the latest state is to do the first render, as well as any changes.

**Option B**
_Component Ready_

This is what you have suggested, though there is something maybe take into consideration with this method.

Try and develop your components to be as dumb as possible. By dumb I mean don't bind everything to a Redux state, unless you are dispatching actions. Have a single top-level Element that pushes state down.

Take this simple application for example:

```html
<my-app>
    <x-title></x-title>
    <x-message></x-message>
    <x-counter>
        <x-label></x-label>
        <x-incr></x-incr>
    </x-counter>
</my-app>
```

So here I can identify that there are two elements that need binding, which are `<my-app>` and `<x-incr>`. All other components should be given their properties. So `<my-app>` binds to Redux for the stores state, `<x-incr>` binds so that it dispatch an action. From here `<my-app>` pushes down the values from the state to the other remaining components, `<x-title>`, `<x-message>` and `<x-label`.

The reason I outline this is because now `<my-app>` could now be in charge of anything to do with state; initial state, loading state, changing state.

I hope this helps, but I think you're definitely on the right track.

Thanks, enjoy :)
