### ISSUE TITLE
Does it notify on subpath change?

### ISSUE THREAD

**Issue by lowiq3** [tur-nr/polymer-redux#51]
https://github.com/tur-nr/polymer-redux/blob/master/polymer-redux.js#L94

My question is if the object reference referred by the path hasn't change, but some sub-property of the object changed, isn't this line preventing notify on such case?

Or put it this way, can I statePath "root.foo.bar" to a property but get notification on "root.foo.bar.*" (sub-property changes)?

Thanks for answering!

**Comment by lowiq3** [comment]
I apologize for reusing this issue for an unrelated question. 
Does this line still set a readOnly property? If it's readonly, why do we set it?
https://github.com/tur-nr/polymer-redux/blob/master/polymer-redux.js#L115

**Comment by kristfal** [comment]
Hey! You can think of whatever you have bound via `statePath` as a regular object binding in polymer. This works just fine:

```

properties: {
  
  object: {
    type: Object,
    statePath: 'app.obj'
  },

  array: {
    type: Array,
    statePath: 'app.arr'
  }
  
},

observers: [
  '_onSubPropChange(object.*),   // Fires on 'app.obj.bar' changes or any other subprop
  '_onSplicesChange(array.splices) // Fires on array splices
]

```

About `readOnly`: When using two way data bindings, `readOnly` makes sense because you want to prevent external elements from changing internal properties of an element. Typically, you'd pair `readOnly` with `notify` to indicate that a data binding is a one-way upward binding.

With redux, that notion is not required as you don't expect elements bound to the redux store to have it's properties changed by parent elements (you can, but you shouldn't mix the concepts), nor should you have elements notifying parent elements about redux changes. In those cases, parent elements should be directly bound to your redux store as well.

In short, when binding data from redux, you shouldn't really care about setting the property to `readOnly`. 

The line of code you highlighted is required to notify property changes in case the property that was about to be changed was 'readOnly', and that the change itself was a sub-property of that object.

If you haven't already, I suggest you follow the [Redux Polycast](https://www.youtube.com/watch?v=PahsgJn0sgU&list=PLNYkxOF6rcIDdS7HWIC_BYRunV6MHs5xo) and try to extend that app with test cases and experiments to answer your own questions.

We've migrated to `polymer–redux` in several large scale production apps and had them running for a couple of months – and we're very happy about it. It is a lot easier to manage state and extend functionality with redux, so if you're heading that way, don't give up if it feels a bit strange in the beginning.
