### ISSUE TITLE
statePath function invoked with old value

### ISSUE THREAD

**Issue by DerekLiang** [tur-nr/polymer-redux#56]
When the statePath function was called, the old component value gets passed in, as demostrated in the following repo https://github.com/DerekLiang/polymer-redux-example/commit/fcb632b8a9bd8d826f37ecfeb4941984004fb7aa

It is a simple one page 2 component app that shows customer age and name, also the customer age in written number.

On the initial load, `number` and `writtenNumber` properties match in `written-number` component. However the user change the age by clicking the `+` or `-` buttons, the two value out of sync.

Further investigation shows that the previous value gets passed into the statePath function which cause the issue.

**Comment by tur-nr** [comment]
This is an outcome of using a Polymer property to find state within a Redux dispatch. Redux will always be one step ahead of Polymer. This is by design to allow the data to change first then Polymer reacts to this change.

The logic you have is expected, here's why:

1. Initial state, all properties set correctly.
2. Dispatch an increase.
3. Reducer increases number.
4. Bindings is triggered.
5. `written-number.writtenNumber` fetches value.
6. Bindings updated.
7. Polymer checks for updates.
8. Polymer updates components.
9. `written-number.number` gets updated.

No. 5 and no. 9 are your key points in this update cycle. Your state is being fetched, and the Polymer property hasn't reacted to the change yet.

I hope this makes sense.

**Comment by tur-nr** [comment]
This is actually something good to note in the documentation maybe as part of #13

**Comment by DerekLiang** [comment]
It worked if i changed to 
```
statePath: function(state) {
           this.async(function() {
             this.writtenNumber = state.numberMap[this.number];
           }.bind(this));
}
```

that will change the execution order no.5 and no9. However it will really  be nice to have this to be built in.

**Comment by tur-nr** [comment]
Not really, I think you need to change how you approach using PolymerRedux.
Ideally the `written-number` should not be bound to the redux store. It
should be given the `numberMap` from the higher order component.

Yes the code works, but you need to take into account that the redux
bindings controls property updates in polymer. Therefore if you use a
polymer property whilst updating is happening, you will have this issue.
