### ISSUE TITLE
Best practices for mocking redux with polymer 2

### ISSUE THREAD

**Issue by idoshamun** [tur-nr/polymer-redux#75]
What are the best practices for mocking `ReduxMixin`?
I want to create a test with an initial Redux state and not sure how to do it.

Here is what I tried:
```
stubReduxStore(state) {
      const sandbox = sinon.sandbox.create();
      return {
        getState: () => state,
        dispatch: sandbox.stub(),
        subscribe: sandbox.stub(),
      };
    },

const state = {
          stress: Immutable.fromJS({
            timeForTask: 100,
          }),
        };

const store = Helpers.stubReduxStore(state);
const oldReduxMixin = window.ReduxMixin;
window.ReduxMixin = PolymerRedux(store);
```

But for some reason when initializing my element it uses the original redux mixin and not my mock

**Comment by pdesjardins90** [comment]
I would suggest giving a look at [redux mock store](https://github.com/arnaudbenard/redux-mock-store) but you're gonna need browserify or something to make it browser-compatible since the author doesn't seem to want to include a browser-friendly version in the distribution. 

What I do with it in a wct context is something like:

```html 
    <test-fixture id="default">
      <script>
        window.store = window.mockStore({
          someReducer: {
            someProperty: 'someValue'
          },
          someOtherReducer: {
            someProperty: 'someValue'
          }
        })

        Polymer.Base.importHref('/src/my-component.html')
      </script>
      <template>
        <my-component></my-component>
      </template>
    </test-fixture>
```

I'm still trying to find a better approach, but that worked for me so far.
